Repository falcosecurity/k8s-metacollector, pull requests merged in 2023-11, with the labels that each got.

#72 docs(README.md): add scope and status badges
  README.md
Labels: dco-signoff: yes, approved, size/S, lgtm

#73 new(ci): add codeql workflow
  .github/workflows/codeql-analysis.yaml
Labels: dco-signoff: yes, approved, lgtm, size/M

#74 fix(go.mod): change the module path to reflect the new repository
  broker/blockingChannel.go
  broker/broker.go
  broker/metrics.go
  broker/queue.go
  collectors/dispatch.go
  collectors/endpoints.go
  collectors/endpointslices.go
  collectors/metrics.go
  collectors/options.go
  collectors/partialObjectMetadata.go
  collectors/pod.go
  collectors/services.go
  collectors/transformers.go
  go.mod
  main.go
  metadata/metrics.go
  metadata/server.go
  pkg/events/cache.go
  pkg/events/event.go
  pkg/events/interface.go
  pkg/events/types.go
  pkg/subscriber/types.go
Labels: dco-signoff: yes, approved, lgtm, size/L

#76 new(version): add new version flag
  Makefile
  main.go
  pkg/version/doc.go
  pkg/version/version.go
Labels: dco-signoff: yes, approved, lgtm, size/M

#77 new(CI): add integration workflow
  .github/workflows/docker-image.yaml
  .github/workflows/integration.yaml
  build/Dockerfile
Labels: dco-signoff: yes, approved, lgtm, size/L

#78 update(makefile): remove unused targets
  Makefile
Labels: dco-signoff: yes, approved, lgtm, size/M

#79 cleanup(hack): remove hack folder
  hack/boilerplate.go.txt
Labels: dco-signoff: yes, approved, size/S, lgtm

#80 fix(manifests): use image from falcosecurity org
  manifests/meta-collector.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#81 new(test_server): add a new test server
  test/server/.gitignore
  test/server/README.md
  test/server/go.mod
  test/server/go.sum
  test/server/main.go
  test/server/test.json
Labels: dco-signoff: yes, approved, lgtm, size/XXL

#83 cleanup(pkg/fields): remove unused fields
  pkg/fields/fields.go
Labels: dco-signoff: yes, approved, lgtm, size/M, cleanup, library

#85 new: add k8s-metacollector binary to `.gitignore`
  .gitignore
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup
