Repository falcosecurity/k8s-metacollector, pull requests merged in 2024-06, with the labels that each got.

#103 fix(events): do not derefence nil pointer
  go.mod
  pkg/events/owner.go
  pkg/events/owner_test.go
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/M

#104 chore(ci): update cosign to v3.5.0
  .github/workflows/docker-image.yaml
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/library

#106 chore(build): upgrade slsa framework and verifier
  .github/workflows/release.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/library
